name: pynetcf
dependencies:
- curl=7.45.0
- hdf5=1.8.15.1
- libnetcdf=4.3.3.1
- mkl=11.3.3
- netcdf4=1.2.2
- numpy
- pandas=0.19.1
- proj4
- pyflakes=1.1.0
- pyproj
- pytest=3.1.2
- pip:
  - autopep8==1.2.2
  - backports.shutil-get-terminal-size==1.0.0
  - coverage==4.1
  - decorator==4.0.9
  - ipdb==0.10.0
  - ipython==4.2.0
  - ipython-genutils==0.1.0
  - pathlib2==2.1.0
  - pep8==1.7.0
  - pexpect==4.1.0
  - pickleshare==0.7.2
  - ptyprocess==0.5.1
  - pygeobase==0.3.9
  - pygeogrids==0.1.9
  - pykdtree==1.1.1
  - pytest-cov==2.2.1
  - simplegeneric==0.8.1
  - traitlets==4.2.1

